name: Azure Login with Service Principal

on:
  push:
    branches:
      - main

jobs:
  azure-login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run az command
      run: az account show
